export const GET_CHARACTER_BY_ID = 'Get character by id'
export const GET_CHARACTER_BY_CATEGORY = 'Get character by category'
export const GET_RANDOM_CHARACTER = 'Get random character'
export const SEARCH_CHARACTER_BY_NAME = 'Search character by name'

export const GET_QUOTE_BY_ID = 'Get quote by id'
export const GET_QUOTES_BY_SERIES = 'Get quotes by series'
export const GET_A_RANDOM_QUOTE = 'Get a random quote'
export const GET_QUOTE_BY_AUTHOR = 'Get quote by author'
export const GET_A_RANDOM_QUOTE_BY_AUTHOR = 'Get a random quote by author'
